foleys_gui_magic: EditorPanels Class Reference
EditorPanels Class Reference
Inherits Component.
Public Member Functions
EditorPanels (MagicBuilder &builder)
void setSelectedNode (const juce::ValueTree &node)
void update ()
void paint (juce::Graphics &g) override
void resized () override
Constructor & Destructor Documentation
EditorPanels()
EditorPanels (MagicBuilder & builder)
Member Function Documentation
setSelectedNode()
void setSelectedNode (const juce::ValueTree & node)
References PropertiesEditor::setNodeToEdit(), and GUITreeEditor::setSelectedNode().
Referenced by ToolBox::setSelectedNode().
update()
void update ()
References Stylesheet::getCurrentStyle(), MagicBuilder::getStylesheet(), PropertiesEditor::setStyle(), Palette::update(), and GUITreeEditor::updateTree().
Referenced by ToolBox::stateWasReloaded().
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
The documentation for this class was generated from the following files:
foleys_EditorPanels.h
foleys_EditorPanels.cpp