foleys_gui_magic: Stylesheet Class Reference
Stylesheet Class Reference
The Stylesheet class represents all style information.
Public Member Functions
Stylesheet ()=default
void setStyle (const juce::ValueTree &node)
The Stylesheet node in the XML can contain several Styles to select from.
bool setMediaSize (int width, int height)
Set the size of the UI.
void updateValidRanges ()
Reads the range, in which the properties won't change due to conditional classes.
void updateStyleClasses (MagicGUIBuilder &builder)
Read the style classes and connect variables.
juce::var getStyleProperty (const juce::Identifier &name, const juce::ValueTree &node, bool inherit=true, juce::ValueTree *definedHere=nullptr) const
This method traverses the dom and checks each style, if that property was defined.
juce::LookAndFeel * getLookAndFeel (const juce::ValueTree &node) const
Return the LookAndFeel for the node.
juce::Image getBackgroundImage (const juce::ValueTree &node) const
Finds a background image for the given node.
juce::Array< juce::Colour > getBackgroundGradient (const juce::ValueTree &node) const
juce::ValueTree getCurrentStyle () const
juce::ValueTree addNewStyleClass (const juce::String &name, juce::UndoManager *undo)
Add a new style class node, so elements of your GUI can inherit that class.
void deleteStyleClass (const juce::String &name, juce::UndoManager *undo)
Delete a style class.
void registerLookAndFeel (juce::String name, std::unique_ptr< juce::LookAndFeel > lookAndFeel)
With that method you can register your custom LookAndFeel class and apply it to different components.
juce::StringArray getAllClassesNames () const
juce::StringArray getLookAndFeelNames () const
bool isClassNode (const juce::ValueTree &node) const
bool isTypeNode (const juce::ValueTree &node) const
bool isIdNode (const juce::ValueTree &node) const
Static Public Member Functions
static juce::Colour parseColour (const juce::String &name)
This is a slightly more intelligent colour lookup than the JUCE one, as it allows to use colour names, as well as 6 digit colour tuples (JUCE will use red as alpha in that case)
static juce::ValueTree createDefaultStyle ()
This creates a default stylesheet from scratch, to allow the default GUI to look sensible.
Detailed Description
The Stylesheet class represents all style information.
It is organised in types, which corresponds to the Components created, classes that can be referenced by any node, and nodes referenced by id.
Constructor & Destructor Documentation
Stylesheet()
Stylesheet () default
Member Function Documentation
setStyle()
void setStyle (const juce::ValueTree & node)
The Stylesheet node in the XML can contain several Styles to select from.
Use this method to select a style.
setMediaSize()
bool setMediaSize (int width, int height)
Set the size of the UI.
This will be used to resolve the properties from the style classes.
Parameters
width is the width of the UI
height is the height of the UI
Returns
false, if the properties are likely to have changed (because a conditional class became valid or invalid)
Referenced by MagicGUIBuilder::updateLayout().
updateValidRanges()
void updateValidRanges ()
Reads the range, in which the properties won't change due to conditional classes.
Referenced by MagicGUIBuilder::updateLayout().
updateStyleClasses()
void updateStyleClasses (MagicGUIBuilder & builder)
Read the style classes and connect variables.
Parameters
builder is the managed builder instance, so the style class can connect to the variables
getStyleProperty()
juce::var getStyleProperty (const juce::Identifier & name, const juce::ValueTree & node, bool inherit = true, juce::ValueTree * definedHere = nullptr) const
This method traverses the dom and checks each style, if that property was defined.
Parameters
name the name of the property.
node is the node in the DOM. This is used for inheritance by traversing upwards.
Referenced by Decorator::configureComponent(), Stylesheet::getLookAndFeel(), and StylePropertyComponent::lookupValue().
getLookAndFeel()
juce::LookAndFeel * getLookAndFeel (const juce::ValueTree & node) const
Return the LookAndFeel for the node.
Make sure never to remove a LookAndFeel, especially as long as the ComponentTree is still referencing any of them.
Parameters
node is the node in the GUI DOM
References Stylesheet::getStyleProperty().
getBackgroundImage()
juce::Image getBackgroundImage (const juce::ValueTree & node) const
Finds a background image for the given node.
Note that this will only return anything useful, if you have added any actual images into the BinaryData and have enabled the FOLEYS_ENABLE_BINARY_DATA setting in the module page.
Parameters
node is the node in the GUI DOM
getBackgroundGradient()
juce::Array< juce::Colour > getBackgroundGradient (const juce::ValueTree & node) const
parseColour()
juce::Colour parseColour (const juce::String & name) static
This is a slightly more intelligent colour lookup than the JUCE one, as it allows to use colour names, as well as 6 digit colour tuples (JUCE will use red as alpha in that case)
Parameters
name a string representing the colour, can be an actual name or a RGB tuple or ARGB tuple.
getCurrentStyle()
juce::ValueTree getCurrentStyle () const
Referenced by ToolBox::stateWasReloaded().
addNewStyleClass()
juce::ValueTree addNewStyleClass (const juce::String & name, juce::UndoManager * undo)
Add a new style class node, so elements of your GUI can inherit that class.
Parameters
name is the name of the new class. Make sure you only use XML conform identifiers, i.e. characters, numbers but not starting with a number, dash and underscore only.
undo the UndoManager to track the action
deleteStyleClass()
void deleteStyleClass (const juce::String & name, juce::UndoManager * undo)
Delete a style class.
This will not delete references to the class.
Parameters
name the name of the class to be deleted.
undo the UndoManager to track the action
registerLookAndFeel()
void registerLookAndFeel (juce::String name, std::unique_ptr< juce::LookAndFeel > lookAndFeel)
With that method you can register your custom LookAndFeel class and apply it to different components.
Parameters
name the name the LookAndFeel can be referenced in the GUI editor
lookAndFeel is an actual LookAndFeel instance, that is owned by the Stylesheet
Referenced by MagicGUIBuilder::registerJUCELookAndFeels().
createDefaultStyle()
juce::ValueTree createDefaultStyle () static
This creates a default stylesheet from scratch, to allow the default GUI to look sensible.
Referenced by MagicGUIBuilder::updateStylesheet().
getAllClassesNames()
juce::StringArray getAllClassesNames () const
getLookAndFeelNames()
juce::StringArray getLookAndFeelNames () const
Referenced by PropertiesEditor::addDecoratorProperties().
isClassNode()
bool isClassNode (const juce::ValueTree & node) const
isTypeNode()
bool isTypeNode (const juce::ValueTree & node) const
isIdNode()
bool isIdNode (const juce::ValueTree & node) const
The documentation for this class was generated from the following files:
foleys_Stylesheet.h
foleys_Stylesheet.cpp