foleys_gui_magic: MagicPluginEditor Class Reference
MagicPluginEditor Class Reference
This is a generic AudioProcessorEditor, that is completely defined and styled by drag and drop.
Inherits AudioProcessorEditor, and DragAndDropContainer.
Public Member Functions
MagicPluginEditor (MagicProcessorState &processorState)
MagicPluginEditor (MagicProcessorState &processorState, const char *data, const int dataSize)
void restoreGUI (const juce::ValueTree &gui)
Setup a GUI from a previously stored ValueTree.
void restoreGUI (const char *data, const int dataSize)
Setup a GUI from a previously stored ValueTree.
void paint (juce::Graphics &g) override
void resized () override
Detailed Description
This is a generic AudioProcessorEditor, that is completely defined and styled by drag and drop.
There is an XML representation, that can be baked into the project using the BinaryData of Projucer.
Constructor & Destructor Documentation
MagicPluginEditor() [1/2]
MagicPluginEditor (MagicProcessorState & processorState)
References MagicGUIBuilder< AppType >::registerJUCEFactories(), MagicBuilder::registerJUCELookAndFeels(), and MagicBuilder::updateAll().
MagicPluginEditor() [2/2]
MagicPluginEditor (MagicProcessorState & processorState, const char * data, const int dataSize)
References MagicGUIBuilder< AppType >::registerJUCEFactories(), MagicBuilder::registerJUCELookAndFeels(), and MagicPluginEditor::restoreGUI().
Member Function Documentation
restoreGUI() [1/2]
void restoreGUI (const juce::ValueTree & gui)
Setup a GUI from a previously stored ValueTree.
Parameters
gui the ValueTree that defines the GUI of the editor
References MagicBuilder::restoreGUI().
Referenced by MagicPluginEditor::MagicPluginEditor().
restoreGUI() [2/2]
void restoreGUI (const char * data, const int dataSize)
Setup a GUI from a previously stored ValueTree.
This is the usual way to deploy your finished GUI via the Projucer:
AudioProcessorEditor* MyAudioProcessor::createEditor()
{
    auto* editor = new foleys::MagicPluginEditor (magicState);
    editor->restoreGUI (BinaryData::magic_xml, BinaryData::magic_xmlSize);
    return editor;
}
Parameters
data points to the binary data of the XML file
dataSize the number of bytes
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
References MagicProcessorState::setLastEditorSize(), and MagicBuilder::updateLayout().
The documentation for this class was generated from the following files:
foleys_MagicPluginEditor.h
foleys_MagicPluginEditor.cpp