foleys_gui_magic: Container Class Reference
Container Class Reference
The Container is a Decorator, that can hold multiple Components.
Public Types
enum Layout { Contents, FlexBox, Tabbed }
Public Member Functions
Container (MagicGUIBuilder &builder, juce::ValueTree node)
void addChildItem (std::unique_ptr< Decorator > child)
Append a child item.
std::vector< std::unique_ptr< Decorator > >::iterator begin ()
std::vector< std::unique_ptr< Decorator > >::iterator end ()
void setLayoutMode (Layout layout)
Sets the layout mode of the container.
void setEditMode (bool shouldEdit) override
This switches this node and all it's descendents in the edit mode, which means, the components don't react, but instead you can move them around.
void resized () override
bool isContainer () const override
void updateLayout () override
This will trigger a recalculation of the children layout regardless of resized.
void updateContinuousRedraw ()
void setRefreshRate (int refreshRate)
If that container contains MacicPlotComponents, it will be repainted with that FPS.
void configureFlexBox (const juce::ValueTree &node)
Public Member Functions inherited from Decorator
Decorator (MagicGUIBuilder &builder, juce::ValueTree node, std::unique_ptr< juce::Component > wrapped={})
void configureDecorator (Stylesheet &stylesheet, const juce::ValueTree &node)
This will get the necessary information from the stylesheet, using inheritance of nodes if needed, to set the margins/borders etc.
void configureComponent (Stylesheet &stylesheet, const juce::ValueTree &node)
This will get the necessary information from the stylesheet, using inheritance of nodes if needed, to set specific properties for the wrapped component.
void paint (juce::Graphics &g) override
void resized () override
void configureFlexBoxItem (const juce::ValueTree &node)
juce::Component * getWrappedComponent ()
Allows accessing the Component inside that Decorator.
const juce::ValueTree & getConfigNode () const
ClientBounds getClientBounds () const
Additional Inherited Members
Public Attributes inherited from Decorator
juce::Colour backgroundColour { juce::Colours::darkgrey }
juce::Colour borderColour { juce::Colours::silver }
float margin = 5.0f
float padding = 5.0f
float border = 0.0f
float radius = 5.0f
juce::String caption
juce::Justification justification = juce::Justification::centredTop
float captionSize = 20.0f
juce::Colour captionColour = juce::Colours::silver
juce::String tabCaption
juce::Colour tabColour
juce::FlexItem flexItem { juce::FlexItem (*this).withFlex (1.0f) }
MagicGUIBuilder & magicBuilder
Detailed Description
The Container is a Decorator, that can hold multiple Components.
In the editor it is seen as "View". With the setting "display" the layout strategy can be chosen.
Member Enumeration Documentation
Layout
enum Layout strong
Enumerator
Contents
FlexBox
Tabbed
Constructor & Destructor Documentation
Container()
Container (MagicGUIBuilder & builder, juce::ValueTree node)
Member Function Documentation
addChildItem()
void addChildItem (std::unique_ptr< Decorator > child)
Append a child item.
To change the order the flexbox.order is used.
begin()
std::vector< std::unique_ptr< Decorator > >::iterator begin ()
end()
std::vector< std::unique_ptr< Decorator > >::iterator end ()
setLayoutMode()
void setLayoutMode (Layout layout)
Sets the layout mode of the container.
References Container::Tabbed.
setEditMode()
void setEditMode (bool shouldEdit) override virtual
This switches this node and all it's descendents in the edit mode, which means, the components don't react, but instead you can move them around.
Reimplemented from Decorator.
References Decorator::setEditMode().
resized()
void resized () override
References Container::updateLayout().
isContainer()
bool isContainer () const override virtual
Reimplemented from Decorator.
updateLayout()
void updateLayout () override virtual
This will trigger a recalculation of the children layout regardless of resized.
Reimplemented from Decorator.
References Container::FlexBox, Decorator::getClientBounds(), and Container::Tabbed.
Referenced by Container::resized().
updateContinuousRedraw()
void updateContinuousRedraw ()
Referenced by Container::setRefreshRate().
setRefreshRate()
void setRefreshRate (int refreshRate)
If that container contains MacicPlotComponents, it will be repainted with that FPS.
The components will be checked, if a redraw is necessary.
Parameters
refreshRate is the refresh rate to redraw
References Container::updateContinuousRedraw().
configureFlexBox()
void configureFlexBox (const juce::ValueTree & node)
References MagicGUIBuilder::getStyleProperty(), and Decorator::magicBuilder.
The documentation for this class was generated from the following files:
foleys_Container.h
foleys_Container.cpp