foleys_gui_magic: MagicBuilder Class Reference
MagicBuilder Class Reference abstract
The MagicBuilder is responsible to recreate the GUI from a single ValueTree.
Public Member Functions
MagicBuilder ()
virtual ~MagicBuilder ()
void setConfigTree (const juce::ValueTree &config)
Allows to set the GUI definition when reloading.
void restoreGUI (juce::Component &parent)
This triggers the rebuild of the GUI with setting the parent component.
Stylesheet & getStylesheet ()
Grant access to the stylesheet to look up visual and layout properties.
juce::ValueTree & getConfigTree ()
Grants access to the main XML, that holds all information.
juce::ValueTree getGuiRootNode ()
Grants access to the GUI root node.
void updateAll ()
void updateStylesheet ()
This selects the stylesheet node and sets it to the Stylesheet.
void updateComponents ()
Recreates all components from the
tree.
void updateLayout ()
Recalculates the layout of all components.
void registerLookAndFeel (juce::String name, std::unique_ptr< juce::LookAndFeel > lookAndFeel)
With that method you can register your custom LookAndFeel class and apply it to different components.
void registerJUCELookAndFeels ()
Registers automatically the JUCE LookAndFeel classes (V1..V4 at the time of writing)
virtual void registerJUCEFactories ()
Calling this method will register the bundled JUCE factories to give already access to many JUCE Components.
void setColourTranslation (juce::Identifier type, std::vector< std::pair< juce::String, int >> mapping)
For each factory you can register a translation table, which will forward the colours from the Stylesheet to the Components.
int findColourId (juce::Identifier type, juce::Identifier name)
Looks up the ColourId for a given type.
int findColourId (juce::Identifier name)
Looks up the ColourId in all types.
juce::StringArray getAllLayoutPropertyNames () const
Returns all possible properties (except colour names) for the editor.
juce::StringArray getColourNames (juce::Identifier type) const
This method returns the names of colours for a certain Component type.
juce::StringArray getAllColourNames () const
This method collects all names of colours, so the style editor can show a control to edit the colours.
void clearGUI ()
This resets the GUI to show a single empty container.
virtual void createDefaultGUITree (bool keepExisting)=0
This will create a default GUI, in case of AudioProcessors from AudioProcessor::getParameterTree().
void createDefaultFromParameters (juce::ValueTree &node, const juce::AudioProcessorParameterGroup &tree)
This creates a hierarchical DOM according to the parameters defined in an AudioProcessor.
virtual juce::StringArray getFactoryNames () const =0
returns the names of all registered factories
virtual juce::StringArray getParameterNames () const =0
Returns the IDs of AudioProcessorParameters for selection.
virtual juce::StringArray getPlotSourcesNames () const =0
Returns the IDs of MagicPlotSources for selection.
void addSettableProperty (juce::Identifier type, SettableProperty property)
std::vector< SettableProperty > getSettableProperties (juce::Identifier type) const
Protected Member Functions
virtual std::unique_ptr< Decorator > restoreNode (juce::Component &component, const juce::ValueTree &node)=0
Protected Attributes
juce::UndoManager undo
juce::ValueTree config
Stylesheet stylesheet
std::map< juce::Identifier, std::vector< std::pair< juce::String, int > > > colourTranslations
Detailed Description
The MagicBuilder is responsible to recreate the GUI from a single ValueTree.
You can add your own factories to the builder to allow additional components. There is a template available that allows for instance a specific AudioProcessor to be supplied to components, that need it.
Constructor & Destructor Documentation
MagicBuilder()
MagicBuilder ()
~MagicBuilder()
~MagicBuilder () virtual
References MagicBuilder::config.
Member Function Documentation
setConfigTree()
void setConfigTree (const juce::ValueTree & config)
Allows to set the GUI definition when reloading.
References MagicBuilder::config.
Referenced by ToolBox::loadDialog().
restoreGUI()
void restoreGUI (juce::Component & parent)
This triggers the rebuild of the GUI with setting the parent component.
References MagicBuilder::updateAll().
getStylesheet()
Stylesheet & getStylesheet ()
Grant access to the stylesheet to look up visual and layout properties.
References MagicBuilder::stylesheet.
Referenced by PropertiesEditor::addDecoratorProperties(), PropertiesEditor::addNodeProperties(), StylePropertyComponent::lookupValue(), PropertiesEditor::setNodeToEdit(), and ToolBox::stateWasReloaded().
getConfigTree()
juce::ValueTree & getConfigTree ()
Grants access to the main XML, that holds all information.
References MagicBuilder::config.
Referenced by ToolBox::saveDialog(), and GUITreeEditor::updateTree().
getGuiRootNode()
juce::ValueTree getGuiRootNode ()
Grants access to the GUI root node.
References MagicBuilder::config.
updateAll()
void updateAll ()
References MagicBuilder::config, MagicBuilder::updateComponents(), MagicBuilder::updateLayout(), and MagicBuilder::updateStylesheet().
Referenced by MagicBuilder::restoreGUI().
updateStylesheet()
void updateStylesheet ()
This selects the stylesheet node and sets it to the Stylesheet.
If no stylesheet is found, a default one is created.
References MagicBuilder::config, Stylesheet::createDefaultStyle(), and MagicBuilder::undo.
Referenced by MagicGUIBuilder< AppType >::MagicGUIBuilder(), and MagicBuilder::updateAll().
updateComponents()
void updateComponents ()
Recreates all components from the
tree.
If no div tree is found, createDefaultGUITree is called to give subclasses a chance to create a suitable default.
References MagicBuilder::config, MagicBuilder::createDefaultGUITree(), MagicBuilder::restoreNode(), and MagicBuilder::undo.
Referenced by MagicBuilder::updateAll().
updateLayout()
void updateLayout ()
Recalculates the layout of all components.
Referenced by MagicBuilder::updateAll().
registerLookAndFeel()
void registerLookAndFeel (juce::String name, std::unique_ptr< juce::LookAndFeel > lookAndFeel)
With that method you can register your custom LookAndFeel class and apply it to different components.
registerJUCELookAndFeels()
void registerJUCELookAndFeels ()
Registers automatically the JUCE LookAndFeel classes (V1..V4 at the time of writing)
References Stylesheet::registerLookAndFeel(), and MagicBuilder::stylesheet.
registerJUCEFactories()
virtual void registerJUCEFactories () virtual
Calling this method will register the bundled JUCE factories to give already access to many JUCE Components.
Reimplemented in MagicGUIBuilder< AppType >.
setColourTranslation()
void setColourTranslation (juce::Identifier type, std::vector< std::pair< juce::String, int >> mapping)
For each factory you can register a translation table, which will forward the colours from the Stylesheet to the Components.
References MagicBuilder::colourTranslations.
findColourId() [1/2]
int findColourId (juce::Identifier type, juce::Identifier name)
Looks up the ColourId for a given type.
findColourId() [2/2]
int findColourId (juce::Identifier name)
Looks up the ColourId in all types.
Finds only the first hit, if the names are not unique.
getAllLayoutPropertyNames()
juce::StringArray getAllLayoutPropertyNames () const
Returns all possible properties (except colour names) for the editor.
getColourNames()
juce::StringArray getColourNames (juce::Identifier type) const
This method returns the names of colours for a certain Component type.
References MagicBuilder::colourTranslations.
Referenced by PropertiesEditor::addTypeProperties().
getAllColourNames()
juce::StringArray getAllColourNames () const
This method collects all names of colours, so the style editor can show a control to edit the colours.
References MagicBuilder::colourTranslations.
clearGUI()
void clearGUI ()
This resets the GUI to show a single empty container.
References MagicBuilder::config, and MagicBuilder::undo.
Referenced by ToolBox::ToolBox().
createDefaultGUITree()
virtual void createDefaultGUITree (bool keepExisting) pure virtual
This will create a default GUI, in case of AudioProcessors from AudioProcessor::getParameterTree().
Parameters
keepExisting if set to true, it will not change an existing root div tree, if set to false, it will replace any existing data.
Implemented in MagicGUIBuilder< AppType >.
Referenced by ToolBox::ToolBox(), and MagicBuilder::updateComponents().
createDefaultFromParameters()
void createDefaultFromParameters (juce::ValueTree & node, const juce::AudioProcessorParameterGroup & tree)
This creates a hierarchical DOM according to the parameters defined in an AudioProcessor.
getFactoryNames()
virtual juce::StringArray getFactoryNames () const pure virtual
returns the names of all registered factories
Implemented in MagicGUIBuilder< AppType >.
Referenced by PropertiesEditor::setNodeToEdit(), and Palette::update().
getParameterNames()
virtual juce::StringArray getParameterNames () const pure virtual
Returns the IDs of AudioProcessorParameters for selection.
Implemented in MagicGUIBuilder< AppType >.
Referenced by PropertiesEditor::setNodeToEdit().
getPlotSourcesNames()
virtual juce::StringArray getPlotSourcesNames () const pure virtual
Returns the IDs of MagicPlotSources for selection.
Implemented in MagicGUIBuilder< AppType >.
Referenced by PropertiesEditor::setNodeToEdit().
addSettableProperty()
void addSettableProperty (juce::Identifier type, SettableProperty property)
getSettableProperties()
std::vector< SettableProperty > getSettableProperties (juce::Identifier type) const
Referenced by PropertiesEditor::addTypeProperties(), and Decorator::configureComponent().
restoreNode()
virtual std::unique_ptr<Decorator> restoreNode (juce::Component & component, const juce::ValueTree & node) protected pure virtual
Implemented in MagicGUIBuilder< AppType >.
Referenced by MagicBuilder::updateComponents().
Member Data Documentation
undo
juce::UndoManager undo protected
Referenced by MagicBuilder::clearGUI(), MagicBuilder::updateComponents(), and MagicBuilder::updateStylesheet().
config
juce::ValueTree config protected
Referenced by MagicBuilder::clearGUI(), MagicBuilder::getConfigTree(), MagicBuilder::getGuiRootNode(), MagicGUIBuilder< AppType >::MagicGUIBuilder(), MagicBuilder::setConfigTree(), MagicBuilder::updateAll(), MagicBuilder::updateComponents(), MagicBuilder::updateStylesheet(), and MagicBuilder::~MagicBuilder().
stylesheet
Stylesheet stylesheet protected
Referenced by MagicBuilder::getStylesheet(), and MagicBuilder::registerJUCELookAndFeels().
colourTranslations
std::map<juce::Identifier, std::vector<std::pair<juce::String, int> > > colourTranslations protected
Referenced by MagicBuilder::getAllColourNames(), MagicBuilder::getColourNames(), and MagicBuilder::setColourTranslation().
The documentation for this class was generated from the following files:
foleys_MagicGUIBuilder.h
foleys_MagicGUIBuilder.cpp