foleys_gui_magic: MagicGUIBuilder Class Reference
MagicGUIBuilder Class Reference
The MagicGUIBuilder is responsible to recreate the GUI from a single ValueTree.
Inherits ChangeListener, and Listener.
Public Member Functions
MagicGUIBuilder (MagicProcessorState *magicStateToUse)
virtual ~MagicGUIBuilder ()
void setConfigTree (const juce::ValueTree &config)
Allows to set the GUI definition when reloading.
void restoreGUI (juce::Component &parent)
This triggers the rebuild of the GUI with setting the parent component.
Stylesheet & getStylesheet ()
Grant access to the stylesheet to look up visual and layout properties.
juce::ValueTree & getConfigTree ()
Grants access to the main XML, that holds all information.
juce::ValueTree getGuiRootNode ()
Grants access to the GUI root node.
void updateAll ()
Will call updateStylesheet(), updateComponents(), updateProperties() and updateLayout()
void updateStylesheet ()
This selects the stylesheet node and sets it to the Stylesheet.
void updateComponents ()
Recreates all components from the tree.
void updateProperties (Decorator &item)
Updates the colours and properties for all components.
void updateLayout ()
Recalculates the layout of all components.
void registerFactory (juce::Identifier type, std::function< std::unique_ptr< juce::Component >(const juce::ValueTree &)> factory)
Register a factory for Components to be available in the GUI editor.
void registerLookAndFeel (juce::String name, std::unique_ptr< juce::LookAndFeel > lookAndFeel)
With that method you can register your custom LookAndFeel class and apply it to different components.
void registerJUCELookAndFeels ()
Registers automatically the JUCE LookAndFeel classes (V1..V4 at the time of writing)
void registerJUCEFactories ()
Calling this method will register the bundled JUCE factories to give already access to many JUCE Components.
void setColourTranslation (juce::Identifier type, std::vector< std::pair< juce::String, int >> mapping)
For each factory you can register a translation table, which will forward the colours from the Stylesheet to the Components.
juce::var getStyleProperty (const juce::Identifier &name, const juce::ValueTree &node) const
This method traverses the dom and checks each style, if that property was defined.
int findColourId (juce::Identifier type, juce::Identifier name)
Looks up the ColourId for a given type.
int findColourId (juce::Identifier name)
Looks up the ColourId in all types.
void removeStyleClassReferences (juce::ValueTree tree, const juce::String &name)
This will go through all nodes and delete the reference to a class.
juce::StringArray getColourNames (juce::Identifier type) const
This method returns the names of colours for a certain Component type.
juce::StringArray getAllColourNames () const
This method collects all names of colours, so the style editor can show a control to edit the colours.
void clearGUI ()
This resets the GUI to show a single empty container.
void createDefaultGUITree (bool keepExisting)
This will create a default GUI, in case of AudioProcessors from AudioProcessor::getParameterTree().
void createDefaultFromParameters (juce::ValueTree &node, const juce::AudioProcessorParameterGroup &tree)
This creates a hierarchical DOM according to the parameters defined in an AudioProcessor.
void showOverlayDialog (std::unique_ptr< juce::Component > dialog)
This is used to display a dialog box.
void closeOverlayDialog ()
Closes a possibly open overlay dialog.
juce::StringArray getFactoryNames () const
returns the names of all registered factories
void addSettableProperty (juce::Identifier type, std::unique_ptr< SettableProperty > property)
const std::vector< std::unique_ptr< SettableProperty > > & getSettableProperties (juce::Identifier type) const
void populateSettableOptionsMenu (juce::ComboBox &comboBox, SettableProperty::PropertyType type) const
Return the list of options.
void changeListenerCallback (juce::ChangeBroadcaster *sender) override
juce::var getPropertyDefaultValue (juce::Identifier type, juce::Identifier property) const
Lookup the default value of the property.
MagicProcessorState * getProcessorState ()
juce::UndoManager & getUndoManager ()
Static Public Member Functions
static juce::NamedValueSet makeJustificationsChoices ()
Detailed Description
The MagicGUIBuilder is responsible to recreate the GUI from a single ValueTree.
You can add your own factories to the builder to allow additional components.
Constructor & Destructor Documentation
MagicGUIBuilder()
MagicGUIBuilder (MagicProcessorState * magicStateToUse)
References MagicGUIBuilder::updateStylesheet().
~MagicGUIBuilder()
~MagicGUIBuilder () virtual
Member Function Documentation
setConfigTree()
void setConfigTree (const juce::ValueTree & config)
Allows to set the GUI definition when reloading.
References MagicGUIBuilder::updateAll().
Referenced by ToolBox::loadGUI().
restoreGUI()
void restoreGUI (juce::Component & parent)
This triggers the rebuild of the GUI with setting the parent component.
References MagicGUIBuilder::updateAll().
getStylesheet()
Stylesheet & getStylesheet ()
Grant access to the stylesheet to look up visual and layout properties.
Referenced by PropertiesEditor::addDecoratorProperties(), PropertiesEditor::addNodeProperties(), StylePropertyComponent::lookupValue(), PropertiesEditor::setNodeToEdit(), and ToolBox::stateWasReloaded().
getConfigTree()
juce::ValueTree & getConfigTree ()
Grants access to the main XML, that holds all information.
Referenced by ToolBox::saveGUI(), and GUITreeEditor::updateTree().
getGuiRootNode()
juce::ValueTree getGuiRootNode ()
Grants access to the GUI root node.
updateAll()
void updateAll ()
Will call updateStylesheet(), updateComponents(), updateProperties() and updateLayout()
References MagicGUIBuilder::updateComponents(), MagicGUIBuilder::updateLayout(), MagicGUIBuilder::updateProperties(), and MagicGUIBuilder::updateStylesheet().
Referenced by MagicGUIBuilder::restoreGUI(), and MagicGUIBuilder::setConfigTree().
updateStylesheet()
void updateStylesheet ()
This selects the stylesheet node and sets it to the Stylesheet.
If no stylesheet is found, a default one is created.
References Stylesheet::createDefaultStyle().
Referenced by MagicGUIBuilder::MagicGUIBuilder(), and MagicGUIBuilder::updateAll().
updateComponents()
void updateComponents ()
Recreates all components from the tree.
If no div tree is found, createDefaultGUITree is called to give subclasses a chance to create a suitable default.
References MagicGUIBuilder::createDefaultGUITree().
Referenced by MagicGUIBuilder::updateAll().
updateProperties()
void updateProperties (Decorator & item)
Updates the colours and properties for all components.
References Decorator::configureComponent(), Decorator::configureDecorator(), Decorator::configureFlexBoxItem(), Decorator::getConfigNode(), and Decorator::getWrappedComponent().
Referenced by MagicGUIBuilder::changeListenerCallback(), MagicGUIBuilder::updateAll(), and MagicGUIBuilder::updateLayout().
updateLayout()
void updateLayout ()
Recalculates the layout of all components.
References Stylesheet::setMediaSize(), MagicGUIBuilder::updateProperties(), and Stylesheet::updateValidRanges().
Referenced by MagicGUIBuilder::changeListenerCallback(), MagicGUIBuilder::showOverlayDialog(), and MagicGUIBuilder::updateAll().
registerFactory()
void registerFactory (juce::Identifier type, std::function< std::unique_ptr< juce::Component >(const juce::ValueTree &)> factory)
Register a factory for Components to be available in the GUI editor.
If you need a reference to the application, you can capture that in the factory lambda.
Referenced by MagicGUIBuilder::registerJUCEFactories().
registerLookAndFeel()
void registerLookAndFeel (juce::String name, std::unique_ptr< juce::LookAndFeel > lookAndFeel)
With that method you can register your custom LookAndFeel class and apply it to different components.
registerJUCELookAndFeels()
void registerJUCELookAndFeels ()
Registers automatically the JUCE LookAndFeel classes (V1..V4 at the time of writing)
References Stylesheet::registerLookAndFeel().
registerJUCEFactories()
void registerJUCEFactories ()
Calling this method will register the bundled JUCE factories to give already access to many JUCE Components.
References MagicGUIBuilder::addSettableProperty(), MagicGUIBuilder::registerFactory(), and MagicGUIBuilder::setColourTranslation().
setColourTranslation()
void setColourTranslation (juce::Identifier type, std::vector< std::pair< juce::String, int >> mapping)
For each factory you can register a translation table, which will forward the colours from the Stylesheet to the Components.
Referenced by MagicGUIBuilder::registerJUCEFactories().
getStyleProperty()
juce::var getStyleProperty (const juce::Identifier & name, const juce::ValueTree & node) const
This method traverses the dom and checks each style, if that property was defined.
Parameters
name the name of the property.
node is the node in the DOM. This is used for inheritance by traversing upwards.
Referenced by Container::configureFlexBox().
findColourId() [1/2]
int findColourId (juce::Identifier type, juce::Identifier name)
Looks up the ColourId for a given type.
findColourId() [2/2]
int findColourId (juce::Identifier name)
Looks up the ColourId in all types.
Finds only the first hit, if the names are not unique.
removeStyleClassReferences()
void removeStyleClassReferences (juce::ValueTree tree, const juce::String & name)
This will go through all nodes and delete the reference to a class.
getColourNames()
juce::StringArray getColourNames (juce::Identifier type) const
This method returns the names of colours for a certain Component type.
getAllColourNames()
juce::StringArray getAllColourNames () const
This method collects all names of colours, so the style editor can show a control to edit the colours.
clearGUI()
void clearGUI ()
This resets the GUI to show a single empty container.
Referenced by ToolBox::ToolBox().
createDefaultGUITree()
void createDefaultGUITree (bool keepExisting)
This will create a default GUI, in case of AudioProcessors from AudioProcessor::getParameterTree().
Parameters
keepExisting if set to true, it will not change an existing root div tree, if set to false, it will replace any existing data.
References MagicGUIBuilder::createDefaultFromParameters(), MagicProcessorState::getPlotSourcesNames(), and MagicProcessorState::getProcessor().
Referenced by ToolBox::ToolBox(), and MagicGUIBuilder::updateComponents().
createDefaultFromParameters()
void createDefaultFromParameters (juce::ValueTree & node, const juce::AudioProcessorParameterGroup & tree)
This creates a hierarchical DOM according to the parameters defined in an AudioProcessor.
Referenced by MagicGUIBuilder::createDefaultGUITree().
showOverlayDialog()
void showOverlayDialog (std::unique_ptr< juce::Component > dialog)
This is used to display a dialog box.
It is called by the GUI editor, but in future it might be reached using the configured GUI.
References MagicGUIBuilder::updateLayout().
Referenced by ToolBox::loadDialog(), and ToolBox::saveDialog().
closeOverlayDialog()
void closeOverlayDialog ()
Closes a possibly open overlay dialog.
Referenced by ToolBox::loadDialog(), and ToolBox::saveDialog().
getFactoryNames()
juce::StringArray getFactoryNames () const
returns the names of all registered factories
Referenced by PropertiesEditor::setNodeToEdit(), and Palette::update().
addSettableProperty()
void addSettableProperty (juce::Identifier type, std::unique_ptr< SettableProperty > property)
Referenced by MagicGUIBuilder::registerJUCEFactories().
getSettableProperties()
const std::vector< std::unique_ptr< SettableProperty > > & getSettableProperties (juce::Identifier type) const
Referenced by PropertiesEditor::addTypeProperties(), Decorator::configureComponent(), and MagicGUIBuilder::getPropertyDefaultValue().
populateSettableOptionsMenu()
void populateSettableOptionsMenu (juce::ComboBox & comboBox, SettableProperty::PropertyType type) const
Return the list of options.
makeJustificationsChoices()
juce::NamedValueSet makeJustificationsChoices () static
changeListenerCallback()
void changeListenerCallback (juce::ChangeBroadcaster * sender) override
References MagicGUIBuilder::updateLayout(), and MagicGUIBuilder::updateProperties().
getPropertyDefaultValue()
juce::var getPropertyDefaultValue (juce::Identifier type, juce::Identifier property) const
Lookup the default value of the property.
References MagicGUIBuilder::getSettableProperties().
Referenced by StylePropertyComponent::lookupValue().
getProcessorState()
MagicProcessorState * getProcessorState ()
getUndoManager()
juce::UndoManager & getUndoManager ()
Referenced by StyleBoolPropertyComponent::refresh(), StyleChoicePropertyComponent::refresh(), StyleBoolPropertyComponent::StyleBoolPropertyComponent(), and StylePropertyComponent::StylePropertyComponent().
The documentation for this class was generated from the following files:
foleys_MagicGUIBuilder.h
foleys_MagicGUIBuilder.cpp
foleys_MagicJUCEFactories.cpp