foleys_gui_magic: PropertiesEditor Class Reference
PropertiesEditor Class Reference
Inherits Component, and Listener.
Public Member Functions
PropertiesEditor (MagicBuilder &builder)
void setStyle (juce::ValueTree style)
void setNodeToEdit (juce::ValueTree node, const juce::Identifier &propToScrollTo=juce::Identifier())
juce::ValueTree & getNodeToEdit ()
void addNodeProperties (bool shouldBeOpen, const juce::Identifier &propToScrollTo=juce::Identifier())
void addDecoratorProperties (bool shouldBeOpen, const juce::Identifier &propToScrollTo=juce::Identifier())
void addTypeProperties (juce::Identifier type, juce::Array< juce::PropertyComponent * > additional, bool shouldBeOpen, const juce::Identifier &propToScrollTo=juce::Identifier())
void addFlexItemProperties (bool shouldBeOpen, const juce::Identifier &propToScrollTo=juce::Identifier())
void addFlexContainerProperties (bool shouldBeOpen, const juce::Identifier &propToScrollTo=juce::Identifier())
void paint (juce::Graphics &) override
void resized () override
MagicBuilder & getMagicBuilder ()
Constructor & Destructor Documentation
PropertiesEditor()
PropertiesEditor (MagicBuilder & builder)
References PropertiesEditor::setNodeToEdit().
Member Function Documentation
setStyle()
void setStyle (juce::ValueTree style)
Referenced by ToolBox::stateWasReloaded().
setNodeToEdit()
void setNodeToEdit (juce::ValueTree node, const juce::Identifier & propToScrollTo = juce::Identifier())
References PropertiesEditor::addDecoratorProperties(), PropertiesEditor::addFlexContainerProperties(), PropertiesEditor::addFlexItemProperties(), PropertiesEditor::addNodeProperties(), PropertiesEditor::addTypeProperties(), MagicBuilder::getFactoryNames(), MagicBuilder::getParameterNames(), MagicBuilder::getPlotSourcesNames(), and MagicBuilder::getStylesheet().
Referenced by PropertiesEditor::PropertiesEditor(), ToolBox::setNodeToEdit(), and ToolBox::setSelectedNode().
getNodeToEdit()
juce::ValueTree & getNodeToEdit ()
addNodeProperties()
void addNodeProperties (bool shouldBeOpen, const juce::Identifier & propToScrollTo = juce::Identifier())
References Stylesheet::getAllClassesNames(), and MagicBuilder::getStylesheet().
Referenced by PropertiesEditor::setNodeToEdit().
addDecoratorProperties()
void addDecoratorProperties (bool shouldBeOpen, const juce::Identifier & propToScrollTo = juce::Identifier())
References Stylesheet::getLookAndFeelNames(), and MagicBuilder::getStylesheet().
Referenced by PropertiesEditor::setNodeToEdit().
addTypeProperties()
void addTypeProperties (juce::Identifier type, juce::Array< juce::PropertyComponent * > additional, bool shouldBeOpen, const juce::Identifier & propToScrollTo = juce::Identifier())
References MagicBuilder::getColourNames(), and MagicBuilder::getSettableProperties().
Referenced by PropertiesEditor::setNodeToEdit().
addFlexItemProperties()
void addFlexItemProperties (bool shouldBeOpen, const juce::Identifier & propToScrollTo = juce::Identifier())
Referenced by PropertiesEditor::setNodeToEdit().
addFlexContainerProperties()
void addFlexContainerProperties (bool shouldBeOpen, const juce::Identifier & propToScrollTo = juce::Identifier())
Referenced by PropertiesEditor::setNodeToEdit().
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
getMagicBuilder()
MagicBuilder & getMagicBuilder ()
The documentation for this class was generated from the following files:
foleys_PropertiesEditor.h
foleys_PropertiesEditor.cpp