foleys_gui_magic: GUITreeEditor Class Reference
GUITreeEditor Class Reference
This GUITreeEditor shows the DOM tree for the GUI.
Inherits Component, and Listener.
Public Member Functions
GUITreeEditor (MagicGUIBuilder &builder)
void paint (juce::Graphics &) override
void resized () override
void setValueTree (juce::ValueTree &refTree)
void updateTree ()
void setSelectedNode (const juce::ValueTree &node)
Detailed Description
This GUITreeEditor shows the DOM tree for the GUI.
The order can be dragged within and nodes be selected to edit them in the PropertiesEditor. It also allows copy and paste via CMD+C/V of sub trees.
Constructor & Destructor Documentation
GUITreeEditor()
GUITreeEditor (MagicGUIBuilder & builder)
References GUITreeEditor::setValueTree().
Member Function Documentation
paint()
void paint (juce::Graphics & g) override
resized()
void resized () override
setValueTree()
void setValueTree (juce::ValueTree & refTree)
Referenced by GUITreeEditor::GUITreeEditor(), and GUITreeEditor::updateTree().
updateTree()
void updateTree ()
References MagicGUIBuilder::getConfigTree(), and GUITreeEditor::setValueTree().
Referenced by ToolBox::stateWasReloaded().
setSelectedNode()
void setSelectedNode (const juce::ValueTree & node)
Referenced by ToolBox::setSelectedNode().
The documentation for this class was generated from the following files:
foleys_GUITreeEditor.h
foleys_GUITreeEditor.cpp