foleys_gui_magic: PlotItem Class Reference
PlotItem Class Reference
Public Member Functions
PlotItem (MagicGUIBuilder &builder, const juce::ValueTree &node)
void update () override
In update() the ValueTree properties should be used to set all properties to the component.
std::vector< SettableProperty > getSettableProperties () const override
Override this to return each settable option the designer should be able to configure on your component.
juce::Component * getWrappedComponent () override
Allows accessing the Component inside that GuiItem.
Public Member Functions inherited from GuiItem
GuiItem (MagicGUIBuilder &builder, juce::ValueTree node)
void setColourTranslation (std::vector< std::pair< juce::String, int >> mapping)
For each factory you can register a translation table, which will forward the colours from the Stylesheet to the Components.
juce::StringArray getColourNames () const
Return the names of configurable colours.
juce::var getProperty (const juce::Identifier &property)
Look up a value through the DOM and CSS.
MagicGUIState & getMagicState ()
virtual GuiItem * findGuiItemWithId (const juce::String &name)
Lookup a Component through the tree.
void updateInternal ()
Reread properties from the config ValueTree.
void paint (juce::Graphics &g) final
void resized () override
virtual bool isContainer () const
virtual void createSubComponents ()
virtual void updateLayout ()
This will trigger a recalculation of the children layout regardless of resized.
void configureFlexBoxItem (const juce::ValueTree &node)
juce::Rectangle< int > getClientBounds () const
Returns the bounds of the wrapped Component.
juce::String getTabCaption (const juce::String &defaultName) const
juce::Colour getTabColour () const
juce::FlexItem & getFlexItem ()
Static Public Attributes
static const juce::Identifier pDecay {"plot-decay"}
Additional Inherited Members
Public Attributes inherited from GuiItem
MagicGUIBuilder & magicBuilder
Protected Attributes inherited from GuiItem
juce::ValueTree configNode
juce::FlexItem flexItem { juce::FlexItem (*this).withFlex (1.0f) }
std::vector< std::pair< juce::String, int > > colourTranslation
Constructor & Destructor Documentation
PlotItem()
PlotItem (MagicGUIBuilder & builder, const juce::ValueTree & node)
References MagicPlotComponent::plotColourId, MagicPlotComponent::plotFillColourId, MagicPlotComponent::plotInactiveColourId, MagicPlotComponent::plotInactiveFillColourId, and GuiItem::setColourTranslation().
Member Function Documentation
update()
void update () override virtual
In update() the ValueTree properties should be used to set all properties to the component.
You can use the magicBuilder to resolve properties from CSS. The Colours will be handled by default.
Implements GuiItem.
References GuiItem::configNode, GuiItem::getMagicState(), GuiItem::getProperty(), PlotItem::pDecay, MagicPlotComponent::setDecayFactor(), and MagicPlotComponent::setPlotSource().
getSettableProperties()
std::vector<SettableProperty> getSettableProperties () const override virtual
Override this to return each settable option the designer should be able to configure on your component.
Reimplemented from GuiItem.
References SettableProperty::Choice, GuiItem::configNode, MagicGUIBuilder::createObjectMenu(), GuiItem::magicBuilder, SettableProperty::Number, and PlotItem::pDecay.
getWrappedComponent()
juce::Component* getWrappedComponent () override virtual
Allows accessing the Component inside that GuiItem.
Don't keep this pointer!
Implements GuiItem.
Member Data Documentation
pDecay
const juce::Identifier pDecay {"plot-decay"} static
Referenced by PlotItem::getSettableProperties(), and PlotItem::update().
The documentation for this class was generated from the following file:
foleys_MagicJUCEFactories.cpp