foleys_gui_magic: Decorator Class Reference
Decorator Class Reference
The Decorator class will draw borders and descriptions around widgets, if defined.
Public Member Functions
Decorator (MagicGUIBuilder &builder, juce::ValueTree node, std::unique_ptr< juce::Component > wrapped={})
virtual void setEditMode (bool shouldEdit)
This method sets the GUI in edit mode, that allows to drag the components around.
void configureDecorator (Stylesheet &stylesheet, const juce::ValueTree &node)
This will get the necessary information from the stylesheet, using inheritance of nodes if needed, to set the margins/borders etc.
void configureComponent (Stylesheet &stylesheet, const juce::ValueTree &node)
This will get the necessary information from the stylesheet, using inheritance of nodes if needed, to set specific properties for the wrapped component.
void paint (juce::Graphics &g) override
void resized () override
virtual bool isContainer () const
virtual void updateLayout ()
This will trigger a recalculation of the children layout regardless of resized.
void configureFlexBoxItem (const juce::ValueTree &node)
juce::Component * getWrappedComponent ()
Allows accessing the Component inside that Decorator.
const juce::ValueTree & getConfigNode () const
Public Attributes
juce::Colour backgroundColour { juce::Colours::darkgrey }
juce::Colour borderColour { juce::Colours::silver }
float margin = 5.0f
float padding = 5.0f
float border = 0.0f
float radius = 5.0f
juce::String caption
juce::Justification justification = juce::Justification::centredTop
float captionSize = 20.0f
juce::Colour captionColour = juce::Colours::silver
juce::String tabCaption
juce::Colour tabColour
juce::FlexItem flexItem { juce::FlexItem (*this).withFlex (1.0f) }
Protected Member Functions
juce::Rectangle< int > getClientBounds () const
Protected Attributes
MagicGUIBuilder & magicBuilder
Detailed Description
The Decorator class will draw borders and descriptions around widgets, if defined.
It also owns the Component and the Attachment, in case the Component is connected to an AudioProcessorValueTreeState.
Constructor & Destructor Documentation
Decorator()
Decorator (MagicGUIBuilder & builder, juce::ValueTree node, std::unique_ptr< juce::Component > wrapped = {})
Member Function Documentation
setEditMode()
void setEditMode (bool shouldEdit) virtual
This method sets the GUI in edit mode, that allows to drag the components around.
Reimplemented in Container.
Referenced by Container::setEditMode().
configureDecorator()
void configureDecorator (Stylesheet & stylesheet, const juce::ValueTree & node)
This will get the necessary information from the stylesheet, using inheritance of nodes if needed, to set the margins/borders etc.
for the Decorator.
References Decorator::backgroundColour, Decorator::border, Decorator::borderColour, Decorator::caption, Decorator::captionColour, Decorator::captionSize, Stylesheet::getBackgroundGradient(), Stylesheet::getBackgroundImage(), Stylesheet::getLookAndFeel(), MagicGUIBuilder::getProcessorState(), MagicGUIBuilder::getStyleProperty(), Decorator::justification, Decorator::magicBuilder, MagicGUIBuilder::makeJustificationsChoices(), Decorator::margin, Decorator::padding, Stylesheet::parseColour(), Decorator::radius, Decorator::tabCaption, and Decorator::tabColour.
Referenced by MagicGUIBuilder::updateProperties().
configureComponent()
void configureComponent (Stylesheet & stylesheet, const juce::ValueTree & node)
This will get the necessary information from the stylesheet, using inheritance of nodes if needed, to set specific properties for the wrapped component.
References MagicGUIBuilder::getSettableProperties(), Stylesheet::getStyleProperty(), and Decorator::magicBuilder.
Referenced by MagicGUIBuilder::updateProperties().
paint()
void paint (juce::Graphics & g) override
References Decorator::backgroundColour, Decorator::border, Decorator::borderColour, Decorator::caption, Decorator::captionColour, Decorator::captionSize, Decorator::justification, Decorator::margin, Decorator::padding, and Decorator::radius.
resized()
void resized () override
References Decorator::caption, Decorator::captionSize, Decorator::justification, Decorator::margin, and Decorator::padding.
Referenced by Decorator::updateLayout().
isContainer()
virtual bool isContainer () const virtual
Reimplemented in Container.
updateLayout()
void updateLayout () virtual
This will trigger a recalculation of the children layout regardless of resized.
Reimplemented in Container.
References Decorator::resized().
configureFlexBoxItem()
void configureFlexBoxItem (const juce::ValueTree & node)
References Decorator::flexItem.
Referenced by MagicGUIBuilder::updateProperties().
getWrappedComponent()
juce::Component * getWrappedComponent ()
Allows accessing the Component inside that Decorator.
Don't keep this pointer!
Referenced by MagicGUIBuilder::updateProperties().
getConfigNode()
const juce::ValueTree & getConfigNode () const
Referenced by MagicGUIBuilder::updateProperties().
getClientBounds()
juce::Rectangle< int > getClientBounds () const protected
References Decorator::caption, Decorator::captionSize, Decorator::justification, Decorator::margin, and Decorator::padding.
Referenced by Container::updateLayout().
Member Data Documentation
backgroundColour
juce::Colour backgroundColour { juce::Colours::darkgrey }
Referenced by Decorator::configureDecorator(), and Decorator::paint().
borderColour
juce::Colour borderColour { juce::Colours::silver }
Referenced by Decorator::configureDecorator(), and Decorator::paint().
margin
float margin = 5.0f
Referenced by Decorator::configureDecorator(), Decorator::getClientBounds(), Decorator::paint(), and Decorator::resized().
padding
float padding = 5.0f
Referenced by Decorator::configureDecorator(), Decorator::getClientBounds(), Decorator::paint(), and Decorator::resized().
border
float border = 0.0f
Referenced by Decorator::configureDecorator(), and Decorator::paint().
radius
float radius = 5.0f
Referenced by Decorator::configureDecorator(), and Decorator::paint().
caption
juce::String caption
Referenced by Decorator::configureDecorator(), Decorator::getClientBounds(), Decorator::paint(), and Decorator::resized().
justification
juce::Justification justification = juce::Justification::centredTop
Referenced by Decorator::configureDecorator(), Decorator::getClientBounds(), Decorator::paint(), and Decorator::resized().
captionSize
float captionSize = 20.0f
Referenced by Decorator::configureDecorator(), Decorator::getClientBounds(), Decorator::paint(), and Decorator::resized().
captionColour
juce::Colour captionColour = juce::Colours::silver
Referenced by Decorator::configureDecorator(), and Decorator::paint().
tabCaption
juce::String tabCaption
Referenced by Decorator::configureDecorator().
tabColour
juce::Colour tabColour
Referenced by Decorator::configureDecorator().
flexItem
juce::FlexItem flexItem { juce::FlexItem (*this).withFlex (1.0f) }
Referenced by Decorator::configureFlexBoxItem().
magicBuilder
MagicGUIBuilder& magicBuilder protected
Referenced by Decorator::configureComponent(), Decorator::configureDecorator(), and Container::configureFlexBox().
The documentation for this class was generated from the following files:
foleys_Decorator.h
foleys_Decorator.cpp